## Week 2 workshop

In this week, we'll look at basic pytorch tensor operations. The materials are based on Section 2 of Sebastian Raschka's 1-hour pytorch tutorial, available here: https://sebastianraschka.com/teaching/pytorch-1h/#2-understanding-tensors

First we import torch:

In [1]:
import torch

Next we create some tensors:

In [2]:
# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)
print(tensor0d)

# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d)

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])
print(tensor2d)

# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)

tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


We often need to deal with the specific data types of the numbers stored in a tensor. We can query them and change them:

In [3]:
# Query the data type. It is `int64`, because we constructed the tensor from a python integer.
tensor0d.dtype

torch.int64

In [4]:
# Convert to torch.float32
tensor0d_float = tensor0d.to(torch.float32)
tensor0d_float.dtype

torch.float32

## Tensor shapes and reshaping

Create a tensor with two rows and three columns:

In [5]:
tensor2d = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]]
)
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

The `shape` attribute shows us the number of elements in each dimension:

In [6]:
tensor2d.shape

torch.Size([2, 3])

**Exercise:** Create a 3d tensor with different numbers of element in each dimension and verify that `shape` returns the right answer.

In [7]:
# your code here

The `view()` method changes how the elements in a tensor are allocated to the different dimensions:

In [8]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
tensor2d.view(1, 6)

tensor([[1, 2, 3, 4, 5, 6]])

**Exercise:** Create a 2d tensor with two rows and four columns and then use the `view()` method to change it into a 3d tensor with two elements in each dimension.

In [10]:
# your code here

The `T` attribute transposes a tensor. Note how its output differs from using `view()` to obtain a tensor of the same shape. Can you explain the difference?

In [11]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [12]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Matrix multiplication

We can perform a matrix multiplication between two tensors with the `@` operator:

In [13]:
# define a matrix
M = torch.tensor([[1, 2], [3, 4]])
# and a vector
v = torch.tensor([1, 2])
# multiply
M @ v.view(2, 1)
# do you know why we wrote v.view(2, 1) in the last step? 

tensor([[ 5],
        [11]])

**Exercise:** Can you explain the output of the following code? Why do we get the result we get?

In [14]:
torch.tensor([1, 2, 3, 4, 5]).view(5, 1) @ torch.tensor([[1, 2, 3, 4]])

tensor([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16],
        [ 5, 10, 15, 20]])